name: Django CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies and check project
        run: |
          python -m pip install --upgrade pip virtualenv
          virtualenv env
          source env/bin/activate
          pip install -r requirements.txt
          python manage.py check

  test:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Run tests
        run: |
          python -m pip install --upgrade pip virtualenv
          virtualenv env
          source env/bin/activate
          pip install -r requirements.txt
          python manage.py test taskManager

  oast:
    runs-on: ubuntu-22.04
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Safety scan
        run: |
          docker run --rm -v ${{ github.workspace }}:/src hysnsec/safety check -r requirements.txt --json > oast-results.json
        continue-on-error: true  # allow job to fail without stopping the pipeline

      - name: Upload OAST results
        uses: actions/upload-artifact@v4
        if: always()  # always run, even if previous steps fail
        with:
          name: Safety
          path: oast-results.json

  integration:
    runs-on: ubuntu-22.04
    needs: oast
    steps:
      - name: Run integration placeholder
        run: echo "This is an integration step"

      - name: Simulate failure
        run: exit 1
        continue-on-error: true

  prod:
    runs-on: ubuntu-22.04
    needs: integration
    steps:
      - name: Deploy placeholder
        run: echo "This is a deploy step."

